In [3]:
import pandas as pd
import os
import numpy as np

In [10]:
label_file = r"..\data\ABC2026 Sozolab Challenge\Dataset\5f_label_loc_train.csv"
df_labels = pd.read_csv(label_file)
print(df_labels.head())

   Unnamed: 0.1  Unnamed: 0  activity                 started_at  \
0           170         170  Location  2023-04-10 14:21:46+09:00
1           171         171  Location  2023-04-10 14:21:55+09:00
2           172         172  Location  2023-04-10 14:22:23+09:00
3           173         173  Location  2023-04-10 14:23:29+09:00
4           174         174  Location  2023-04-10 14:23:42+09:00

                 finished_at deleted_at               updated_at  user_id  \
0  2023-04-10 14:21:50+09:00        NaN  2023-04-10 05:22:02 UTC       97
1  2023-04-10 14:22:16+09:00        NaN  2023-04-10 05:23:02 UTC       97
2  2023-04-10 14:23:25+09:00        NaN  2023-04-10 05:24:01 UTC       97
3  2023-04-10 14:23:44+09:00        NaN  2023-04-10 05:24:02 UTC       97
4  2023-04-10 14:24:05+09:00        NaN  2023-04-10 05:25:03 UTC       97

           user           room floor
0  5th-location        kitchen   5th
1  5th-location      cafeteria   5th
2  5th-location        kitchen   5th
3  5th-location       cleaning   5th
4  5th-location  nurse station   5th

In [11]:
df_labels["finished_at"] = pd.to_datetime(df_labels["finished_at"]).dt.tz_convert("Asia/Tokyo").dt.tz_localize(None)
df_labels["started_at"] = pd.to_datetime(df_labels["started_at"]).dt.tz_convert("Asia/Tokyo").dt.tz_localize(None)
df_labels = df_labels.sort_values(by=['started_at'])
df_labels.head()

,Unnamed: 0.1,Unnamed: 0,activity,started_at,finished_at,deleted_at,updated_at,user_id,user,room,floor
0,170,170,Location,2023-04-10 14:21:46,2023-04-10 14:21:50,NaN,2023-04-10 05:22:02 UTC,97,5th-location,kitchen,5th
1,171,171,Location,2023-04-10 14:21:55,2023-04-10 14:22:16,NaN,2023-04-10 05:23:02 UTC,97,5th-location,cafeteria,5th
2,172,172,Location,2023-04-10 14:22:23,2023-04-10 14:23:25,NaN,2023-04-10 05:24:01 UTC,97,5th-location,kitchen,5th
3,173,173,Location,2023-04-10 14:23:29,2023-04-10 14:23:44,NaN,2023-04-10 05:24:02 UTC,97,5th-location,cleaning,5th
4,174,174,Location,2023-04-10 14:23:42,2023-04-10 14:24:05,NaN,2023-04-10 05:25:03 UTC,97,5th-location,nurse station,5th

In [ ]:
df_labels = df_labels.drop(columns=['Unnamed: 0'])

,Unnamed: 0.1,activity,started_at,finished_at,deleted_at,updated_at,user_id,user,room,floor
0,170,Location,2023-04-10 14:21:46,2023-04-10 14:21:50,NaN,2023-04-10 05:22:02 UTC,97,5th-location,kitchen,5th
1,171,Location,2023-04-10 14:21:55,2023-04-10 14:22:16,NaN,2023-04-10 05:23:02 UTC,97,5th-location,cafeteria,5th
2,172,Location,2023-04-10 14:22:23,2023-04-10 14:23:25,NaN,2023-04-10 05:24:01 UTC,97,5th-location,kitchen,5th
3,173,Location,2023-04-10 14:23:29,2023-04-10 14:23:44,NaN,2023-04-10 05:24:02 UTC,97,5th-location,cleaning,5th
4,174,Location,2023-04-10 14:23:42,2023-04-10 14:24:05,NaN,2023-04-10 05:25:03 UTC,97,5th-location,nurse station,5th
...,...,...,...,...,...,...,...,...,...,...
1329,1518,Location,2023-04-13 17:25:12,2023-04-13 17:25:13,NaN,2023-04-13 08:26:02 UTC,91,2nd-location,Cafeteria A,2nd
1330,1519,Location,2023-04-13 17:25:17,2023-04-13 17:28:51,NaN,2023-04-13 08:29:01 UTC,91,2nd-location,Cafeteria D,2nd
1331,1520,Location,2023-04-13 17:28:59,2023-04-13 17:29:04,NaN,2023-04-13 08:30:03 UTC,91,2nd-location,hallway,"2nd,5th"
1332,1521,Location,2023-04-13 17:29:09,2023-04-13 17:29:57,NaN,2023-04-13 08:30:04 UTC,91,2nd-location,201,2nd
1333,1522,Location,2023-04-13 17:29:19,2023-04-13 17:29:59,NaN,2023-04-13 08:31:02 UTC,91,2nd-location,hallway,"2nd,5th"

In [13]:
df_labels['started_at'].isnull().sum()

np.int64(0)

In [15]:
df_labels['finished_at'].isnull().sum()

np.int64(0)

In [16]:
a = df_labels[pd.notnull(df_labels['started_at'])]

In [17]:
b = a[pd.notnull(a['finished_at'])]

In [18]:
dx = b["deleted_at"].dropna()
dx.value_counts().sum()

np.int64(55)

In [19]:
df_cleaned = dfr = b[~b["deleted_at"].isin(dx)]
df_cleaned

,Unnamed: 0.1,Unnamed: 0,activity,started_at,finished_at,deleted_at,updated_at,user_id,user,room,floor
0,170,170,Location,2023-04-10 14:21:46,2023-04-10 14:21:50,NaN,2023-04-10 05:22:02 UTC,97,5th-location,kitchen,5th
1,171,171,Location,2023-04-10 14:21:55,2023-04-10 14:22:16,NaN,2023-04-10 05:23:02 UTC,97,5th-location,cafeteria,5th
2,172,172,Location,2023-04-10 14:22:23,2023-04-10 14:23:25,NaN,2023-04-10 05:24:01 UTC,97,5th-location,kitchen,5th
3,173,173,Location,2023-04-10 14:23:29,2023-04-10 14:23:44,NaN,2023-04-10 05:24:02 UTC,97,5th-location,cleaning,5th
4,174,174,Location,2023-04-10 14:23:42,2023-04-10 14:24:05,NaN,2023-04-10 05:25:03 UTC,97,5th-location,nurse station,5th
...,...,...,...,...,...,...,...,...,...,...,...
1329,1518,1518,Location,2023-04-13 17:25:12,2023-04-13 17:25:13,NaN,2023-04-13 08:26:02 UTC,91,2nd-location,Cafeteria A,2nd
1330,1519,1519,Location,2023-04-13 17:25:17,2023-04-13 17:28:51,NaN,2023-04-13 08:29:01 UTC,91,2nd-location,Cafeteria D,2nd
1331,1520,1520,Location,2023-04-13 17:28:59,2023-04-13 17:29:04,NaN,2023-04-13 08:30:03 UTC,91,2nd-location,hallway,"2nd,5th"
1332,1521,1521,Location,2023-04-13 17:29:09,2023-04-13 17:29:57,NaN,2023-04-13 08:30:04 UTC,91,2nd-location,201,2nd
1333,1522,1522,Location,2023-04-13 17:29:19,2023-04-13 17:29:59,NaN,2023-04-13 08:31:02 UTC,91,2nd-location,hallway,"2nd,5th"